[{if $oView->getClassName() != 'start'}]
    [{* ########### START - change for celebros interface ########################## *}]   
    [{if $oxcmp_shop}]
        [{if $oxcmp_shop->cel_is_active}]
            [{block name="sidebar_cel_refinmentstree"}]
                [{if $aMoreQuestions->Count}]
                    [{include file="cel_refinmentstree.tpl" questions=$aMoreQuestions->Items}]
                [{/if}]
            [{/block}]
        [{else}]
            [{oxid_include_widget cl="oxwCategoryTree" cnid=$oView->getCategoryId() deepLevel=0 noscript=1 nocookie=1}]
        [{/if}]
    [{/if}]	
    [{* ########### END - change for celebros interface ############################# *}] 
[{/if}]